FROM php:7.4.9-fpm

COPY php.ini /usr/local/etc/php/

RUN apt update \
  && apt install -y default-mysql-client zliblg-dev libzip-dev unzip \
  && docker-php-ext-install pdo_mysql zip

RUN curl